### ISSUE TITLE
请问如何取得联系

### ISSUE THREAD

**Issue by rainzee** [cilame/vscrapy#1]

**Comment by cilame** [comment]
向 setup.py 里面的 hotmail 邮箱发送你的联系方式，比如QQ啥的。

________________________________
发件人: rainzee wang <notifications@github.com>
发送时间: 2020年2月26日 18:31
收件人: cilame/vscrapy <vscrapy@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [cilame/vscrapy] 请问如何取得联系 (#1)


―
